#! /bin/sh

# set the background
wal -i "$(ls -lh ~/.cache/wallpaper | sed 's/.*-> //')"
#### autostart ####
# key daemon
pgrep -x sxhkd > /dev/null || sxhkd &
# launch the bar 
~/personal/scripts/bar.sh
# window composer for transparency
# -D option to control the anmation
picom -D 0 &
# workspaces names
bspc monitor -d 1 2 3 4 5 6 7 8 9 
# no borders
bspc config border_width         0
# gaps between menus
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
