#! /bin/sh
# autostart
wal -i "$(ls -lh ~/.cache/wallpaper | sed 's/.*-> //')" &
killall polybar ; polybar bar1 & 
killall sxhkd ; sxhkd &
killall dunst; dunst &
picom &
wmname LG3D


# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

# workspaces names
bspc monitor -d 1 2 3 4 5 6 7 8 9 
# no borders
bspc config border_width         2
# gaps between menus
bspc config window_gap          0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true 
bspc config merge_overlapping true 

bspc rule -a Zathura state=tiled desktop=^3 follow=on
bspc rule -a Eclipse state=floating desktop=^3 follow=on
bspc rule -a Code state=monocale desktop=^3 foloow=on
bspc rule -a jetbrains-clion state=floating desktop=^3 foloow=on
bspc rule -a Alacritty desktop=^2 follow=on
bspc rule -a Brave-browser desktop=^1
